name: zameenclone
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: 0.13.5
  cupertino_icons: ^1.0.2
  shimmer_animation: 2.1.0
  animated_bottom_navigation_bar: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/sliver_bk.png
    - assets/home_sliver_bk.jpg
    - assets/home_sliver_bk.png
    - assets/app_logo.jpg

  uses-material-design: true
