import 'package:flutter/material.dart';

class PostAddPage extends StatefulWidget {
  PostAddPage({Key? key}) : super(key: key);

  @override
  State<PostAddPage> createState() => _PostAddPageState();
}

class _PostAddPageState extends State<PostAddPage> {
  String _selectedCity = 'Karachi';
  String? _selectedLocation;
  List<Map<String, String>> _tmpLocations = [];
  List<Map<String, String>> _locations = [
    {'loc': 'APP Employees Co-operative Housing Society', 'city': 'Karachi'},
    {'loc': 'ASF Housing Scheme', 'city': 'Karachi'},
    {'loc': 'ASF Tower', 'city': 'Karachi'},
    {'loc': 'Abdullah Ahmed Road', 'city': 'Karachi'},
    {'loc': 'Abdullah Haroon Road', 'city': 'Karachi'},
    {'loc': 'Abid Town', 'city': 'Karachi'},
    {'loc': 'Ablagh-e-Aama Society', 'city': 'Karachi'},
    {'loc': 'Abul Hassan Isphani Road', 'city': 'Karachi'},
    {'loc': 'Airport', 'city': 'Karachi'},
    {'loc': 'Airport Road', 'city': 'Karachi'},
    {'loc': 'Aisha Manzil', 'city': 'Karachi'},
    {'loc': 'Al-Hilal Society', 'city': 'Karachi'},
    {'loc': 'Allama Iqbal Town', 'city': 'Karachi'},
    {'loc': 'Amil Colony', 'city': 'Karachi'},
    {'loc': 'Amir Khusro', 'city': 'Karachi'},
    {'loc': 'Anda Mor Road', 'city': 'Karachi'},
    {'loc': 'Ashraf Nagar', 'city': 'Karachi'},
    {'loc': 'Azam Nagar', 'city': 'Karachi'},
    {'loc': 'Azam Town', 'city': 'Karachi'},
    {'loc': 'BMCHS', 'city': 'Karachi'},
    {'loc': 'Bahria Town Karachi', 'city': 'Karachi'},
    {'loc': 'Baldia Town', 'city': 'Karachi'},
    {'loc': 'Baloch Colony', 'city': 'Karachi'},
    {'loc': 'Bath Island', 'city': 'Karachi'},
    {'loc': 'Bilal Town', 'city': 'Karachi'},
    {'loc': 'Bin Qasim Town', 'city': 'Karachi'},
    {'loc': 'Bolton Market', 'city': 'Karachi'},
    {'loc': 'Britto Road', 'city': 'Karachi'},
    {'loc': 'Callachi Cooperative Housing Society', 'city': 'Karachi'},
    {'loc': 'Cantt', 'city': 'Karachi'},
    {'loc': 'Chapal Courtyard', 'city': 'Karachi'},
    {'loc': 'Chapal Uptown', 'city': 'Karachi'},
    {'loc': 'Civil Lines', 'city': 'Karachi'},
    {'loc': 'Clifton', 'city': 'Karachi'},
    {'loc': 'Comissioner Coop Housing Society', 'city': 'Karachi'},
    {'loc': 'Commissioner Society', 'city': 'Karachi'},
    {'loc': 'Cosmopolitan Society', 'city': 'Karachi'},
    {'loc': 'Cotton Export Cooperative Housing Society', 'city': 'Karachi'},
    {'loc': 'Cutchi Memon Cooperative Housing Society', 'city': 'Karachi'},
    {'loc': 'DHA City Karachi', 'city': 'Karachi'},
    {'loc': 'DHA Defence', 'city': 'Karachi'},
    {'loc': 'Dalmia Cement Factory Road', 'city': 'Karachi'},
    {'loc': 'Damba', 'city': 'Karachi'},
    {'loc': 'Darul Aman Society', 'city': 'Karachi'},
    {'loc': 'Dastgir Colony', 'city': 'Karachi'},
    {'loc': 'Defence Garden', 'city': 'Karachi'},
    {'loc': 'Defence View Society', 'city': 'Karachi'},
    {'loc': 'Delhi Colony', 'city': 'Karachi'},
    {'loc': 'Dhabeji', 'city': 'Karachi'},
    {'loc': 'Dr Daud Pota Road', 'city': 'Karachi'},
    {'loc': 'Erum Villas', 'city': 'Karachi'},
    {'loc': 'Falaknaz Dynasty', 'city': 'Karachi'},
    {'loc': 'Falcon Complex Faisal', 'city': 'Karachi'},
    {'loc': 'Farhan Dream Land', 'city': 'Karachi'},
    {'loc': 'Federal B Area', 'city': 'Karachi'},
    {'loc': 'Frere Town', 'city': 'Karachi'},
    {'loc': 'Gadap Road', 'city': 'Karachi'},
    {'loc': 'Gadap Town', 'city': 'Karachi'},
    {'loc': 'Garden West', 'city': 'Karachi'},
    {'loc': 'Gizri', 'city': 'Karachi'},
    {'loc': 'Gizri Road', 'city': 'Karachi'},
    {'loc': 'Gohar Green City', 'city': 'Karachi'},
    {'loc': 'Golimar', 'city': 'Karachi'},
    {'loc': 'Goth Ibrahim Haidri', 'city': 'Karachi'},
    {'loc': 'Gujjar Chowk', 'city': 'Karachi'},
    {'loc': 'Gulbai', 'city': 'Karachi'},
    {'loc': 'Gulberg Town', 'city': 'Karachi'},
    {'loc': 'Gulistan-e-Jauhar', 'city': 'Karachi'},
    {'loc': 'Gulistan-e-Malir', 'city': 'Karachi'},
    {'loc': 'Gulshan-E-Faisal', 'city': 'Karachi'},
    {'loc': 'Gulshan-e-Amin', 'city': 'Karachi'},
    {'loc': 'Gulshan-e-Areesha', 'city': 'Karachi'},
    {'loc': 'Gulshan-e-Iqbal Town', 'city': 'Karachi'},
    {'loc': 'Gulshan-e-Jami', 'city': 'Karachi'},
    {'loc': 'Gulshan-e-Malir', 'city': 'Karachi'},
    {'loc': 'Gulshan-e-Mustafa', 'city': 'Karachi'},
    {'loc': 'Gulshan-e-Tauheed', 'city': 'Karachi'},
    {'loc': 'Gulshan-e-Umair', 'city': 'Karachi'},
    {'loc': 'Gulshan-e-Usman Housing Society', 'city': 'Karachi'},
    {'loc': 'Guru Mandir Chorangi', 'city': 'Karachi'},
    {'loc': 'Hazara Colony', 'city': 'Karachi'},
    {'loc': 'Hill Park', 'city': 'Karachi'},
    {'loc': 'Hub River Road', 'city': 'Karachi'},
    {'loc': 'Hyderi', 'city': 'Karachi'},
    {'loc': 'I.I. Chundrigar Road', 'city': 'Karachi'},
    {'loc': 'Jahanabad', 'city': 'Karachi'},
    {'loc': 'Jamaluddin Afghani Road', 'city': 'Karachi'},
    {'loc': 'Jamshed Road', 'city': 'Karachi'},
    {'loc': 'Jamshed Town', 'city': 'Karachi'},
    {'loc': 'Jinnah Avenue', 'city': 'Karachi'},
    {'loc': 'KDA Scheme 1', 'city': 'Karachi'},
    {'loc': 'Kamran Chowrangi', 'city': 'Karachi'},
    {'loc': 'Karachi - Hyderabad Motorway', 'city': 'Karachi'},
    {'loc': 'Karachi Motorway', 'city': 'Karachi'},
    {'loc': 'Kashmir Colony', 'city': 'Karachi'},
    {'loc': 'Kashmir Road', 'city': 'Karachi'},
    {'loc': 'Kemari Town', 'city': 'Karachi'},
    {'loc': 'Khalid Bin Walid Road', 'city': 'Karachi'},
    {'loc': 'Khaliq-uz-Zaman Road', 'city': 'Karachi'},
    {'loc': 'Khayaban-e-Ittehad Road', 'city': 'Karachi'},
    {'loc': 'Khuda Ki Basti', 'city': 'Karachi'},
    {'loc': 'Khudadad Colony', 'city': 'Karachi'},
    {'loc': 'Korangi', 'city': 'Karachi'},
    {'loc': 'Lalukhet', 'city': 'Karachi'},
    {'loc': 'Landhi', 'city': 'Karachi'},
    {'loc': 'Laraib Garden', 'city': 'Karachi'},
    {'loc': 'Liaquat Avenue', 'city': 'Karachi'},
    {'loc': 'Liaquatabad', 'city': 'Karachi'},
    {'loc': 'Lines Area', 'city': 'Karachi'},
    {'loc': 'Lyari Expressway', 'city': 'Karachi'},
    {'loc': 'Lyari Town', 'city': 'Karachi'},
    {'loc': 'M.A. Jinnah Road', 'city': 'Karachi'},
    {'loc': 'MT Khan Road', 'city': 'Karachi'},
    {'loc': 'Malir', 'city': 'Karachi'},
    {'loc': 'Malir Housing Scheme 1', 'city': 'Karachi'},
    {'loc': 'Malir Link To Super Highway', 'city': 'Karachi'},
    {'loc': 'Manghopir Road', 'city': 'Karachi'},
    {'loc': 'Mangopir', 'city': 'Karachi'},
    {'loc': 'Manzoor Colony', 'city': 'Karachi'},
    {'loc': 'Maskan Chowrangi', 'city': 'Karachi'},
    {'loc': 'Mauripur Road', 'city': 'Karachi'},
    {'loc': 'Mehmoodabad', 'city': 'Karachi'},
    {'loc': 'Metrovil Colony', 'city': 'Karachi'},
    {'loc': 'Muslimabad Society', 'city': 'Karachi'},
    {'loc': 'Nafeesabad', 'city': 'Karachi'},
    {'loc': 'National Highway', 'city': 'Karachi'},
    {'loc': 'Naval Colony', 'city': 'Karachi'},
    {'loc': 'Navy Housing Scheme Karsaz', 'city': 'Karachi'},
    {'loc': 'Nawab Siddique Ali Khan Road', 'city': 'Karachi'},
    {'loc': 'Nawaz Sharif Housing Scheme', 'city': 'Karachi'},
    {'loc': 'Naya Nazimabad', 'city': 'Karachi'},
    {'loc': 'Nazimabad', 'city': 'Karachi'},
    {'loc': 'New Karachi', 'city': 'Karachi'},
    {'loc': 'New Lyari Expressway Road', 'city': 'Karachi'},
    {'loc': 'Nishtar Road ', 'city': 'Karachi'},
    {'loc': 'Noor Muhammad Goth', 'city': 'Karachi'},
    {'loc': 'Nooriabad', 'city': 'Karachi'},
    {'loc': 'North Karachi', 'city': 'Karachi'},
    {'loc': 'North Nazimabad', 'city': 'Karachi'},
    {'loc': 'Northern Bypass', 'city': 'Karachi'},
    {'loc': 'Numaish Chowrangi', 'city': 'Karachi'},
    {'loc': 'Oasis Park Residencia', 'city': 'Karachi'},
    {'loc': 'Old Clifton', 'city': 'Karachi'},
    {'loc': 'Old Jamia Millia Road', 'city': 'Karachi'},
    {'loc': 'Old Ravians Co-Operative Housing Society', 'city': 'Karachi'},
    {'loc': 'Orangi Town', 'city': 'Karachi'},
    {'loc': 'Others', 'city': 'Karachi'},
    {'loc': 'P & T Colony', 'city': 'Karachi'},
    {'loc': 'PAF Housing Scheme', 'city': 'Karachi'},
    {'loc': 'PIB Colony', 'city': 'Karachi'},
    {'loc': 'PIDC', 'city': 'Karachi'},
    {'loc': 'Pakistan Chowk', 'city': 'Karachi'},
    {'loc': 'Peoples Colony', 'city': 'Karachi'},
    {'loc': 'Police Society', 'city': 'Karachi'},
    {'loc': 'Punjab Chowrangi', 'city': 'Karachi'},
    {'loc': 'Punjab Colony', 'city': 'Karachi'},
    {'loc': 'Qayyumabad', 'city': 'Karachi'},
    {'loc': 'Rabia City', 'city': 'Karachi'},
    {'loc': 'Ranchore Line Bazar', 'city': 'Karachi'},
    {'loc': 'Rashid Minhas Road', 'city': 'Karachi'},
    {'loc': 'Rizvia Society', 'city': 'Karachi'},
    {'loc': 'Royal Defence Tower', 'city': 'Karachi'},
    {'loc': 'Rufi Lake Drive Apartments', 'city': 'Karachi'},
    {'loc': 'Rufi Rose Petals', 'city': 'Karachi'},
    {'loc': 'Saadi Road', 'city': 'Karachi'},
    {'loc': 'Saddar Town', 'city': 'Karachi'},
    {'loc': 'Saima Luxury Homes', 'city': 'Karachi'},
    {'loc': 'Sakhi Hassan Chowrangi', 'city': 'Karachi'},
    {'loc': 'Scheme 33', 'city': 'Karachi'},
    {'loc': 'Scheme 45', 'city': 'Karachi'},
    {'loc': 'Sea View Apartments', 'city': 'Karachi'},
    {'loc': 'Seven Wonders City', 'city': 'Karachi'},
    {'loc': 'Shadman 2', 'city': 'Karachi'},
    {'loc': 'Shah Faisal Town', 'city': 'Karachi'},
    {'loc': 'Shaheed Millat Road', 'city': 'Karachi'},
    {'loc': 'Shaheed-e-Millat Expressway', 'city': 'Karachi'},
    {'loc': 'Shahra-e-Faisal', 'city': 'Karachi'},
    {'loc': 'Shahra-e-Jahangir', 'city': 'Karachi'},
    {'loc': 'Shahra-e-Liaquat', 'city': 'Karachi'},
    {'loc': 'Shahra-e-Qaideen', 'city': 'Karachi'},
    {'loc': 'Shahra-e-Usman', 'city': 'Karachi'},
    {'loc': 'Shahrah-e-Pakistan', 'city': 'Karachi'},
    {'loc': 'Sharafi Goth', 'city': 'Karachi'},
    {'loc': 'Sher Shah Suri Road', 'city': 'Karachi'},
    {'loc': 'Siemens Chowrangi', 'city': 'Karachi'},
    {'loc': 'Sindh Industrial Trading Estate ', 'city': 'Karachi'},
    {'loc': 'Sir Shah Muhammad Suleman Road', 'city': 'Karachi'},
    {'loc': 'Stadium Road', 'city': 'Karachi'},
    {'loc': 'State Bank of Pakistan Staff Co-Operative Housing Society', 'city': 'Karachi'},
    {'loc': 'Suparco Road', 'city': 'Karachi'},
    {'loc': 'Super Highway', 'city': 'Karachi'},
    {'loc': 'Surti Muslim Co-Operative Housing Society', 'city': 'Karachi'},
    {'loc': 'Tahir Villa', 'city': 'Karachi'},
    {'loc': 'Tariq Road', 'city': 'Karachi'},
    {'loc': 'Teacher Society', 'city': 'Karachi'},
    {'loc': 'Times Residency', 'city': 'Karachi'},
    {'loc': 'Tipu Sultan Road', 'city': 'Karachi'},
    {'loc': 'University Road', 'city': 'Karachi'},
    {'loc': 'Yousaf Goth', 'city': 'Karachi'},
    {'loc': 'Zamzama', 'city': 'Karachi'},
    {'loc': 'circular road', 'city': 'Karachi'},
    {'loc': 'Aabpara Coop Housing Society', 'city': 'Lahore'},
    {'loc': 'Aaqa Society', 'city': 'Lahore'},
    {'loc': 'Aashiana Road', 'city': 'Lahore'},
    {'loc': 'Abbot Road', 'city': 'Lahore'},
    {'loc': 'Abdali Road', 'city': 'Lahore'},
    {'loc': 'Abdalians Cooperative Housing Society', 'city': 'Lahore'},
    {'loc': 'Abdul Sattar Edhi Road', 'city': 'Lahore'},
    {'loc': 'Abid Market', 'city': 'Lahore'},
    {'loc': 'Abid Road', 'city': 'Lahore'},
    {'loc': 'Adams Housing Scheme', 'city': 'Lahore'},
    {'loc': 'Adan Villas', 'city': 'Lahore'},
    {'loc': 'Aftab Garden', 'city': 'Lahore'},
    {'loc': 'Afzal Park', 'city': 'Lahore'},
    {'loc': 'Agrics Town', 'city': 'Lahore'},
    {'loc': 'Ahbab Colony', 'city': 'Lahore'},
    {'loc': 'Ahlu Road', 'city': 'Lahore'},
    {'loc': 'Ahmad Avenue', 'city': 'Lahore'},
    {'loc': 'Ahmad Housing Society', 'city': 'Lahore'},
    {'loc': 'Ahmed Colony', 'city': 'Lahore'},
    {'loc': 'Airline Housing Society', 'city': 'Lahore'},
    {'loc': 'Airport Road', 'city': 'Lahore'},
    {'loc': 'Aitchison Society', 'city': 'Lahore'},
    {'loc': 'Al Faisal Town', 'city': 'Lahore'},
    {'loc': 'Al Hamad Colony', 'city': 'Lahore'},
    {'loc': 'Al Hamra Town', 'city': 'Lahore'},
    {'loc': 'Al Haram Garden', 'city': 'Lahore'},
    {'loc': 'Al Jalil Garden', 'city': 'Lahore'},
    {'loc': 'Al Jannat Housing Scheme', 'city': 'Lahore'},
    {'loc': 'Al Madina Avenue', 'city': 'Lahore'},
    {'loc': 'Al Noor Park Housing Society', 'city': 'Lahore'},
    {'loc': 'Al Noor Town', 'city': 'Lahore'},
    {'loc': 'Al Raheem Town', 'city': 'Lahore'},
    {'loc': 'Al Rahim Homes', 'city': 'Lahore'},
    {'loc': 'Al Rehman Garden', 'city': 'Lahore'},
    {'loc': 'Al-Amin Housing Society', 'city': 'Lahore'},
    {'loc': 'Al-Hadi Garden', 'city': 'Lahore'},
    {'loc': 'Al-Hafeez Garden Road', 'city': 'Lahore'},
    {'loc': 'Al-Hafiz Town', 'city': 'Lahore'},
    {'loc': 'Al-Hamad Colony ', 'city': 'Lahore'},
    {'loc': 'Al-Hamd Garden', 'city': 'Lahore'},
    {'loc': 'Al-Hamd Park', 'city': 'Lahore'},
    {'loc': 'Al-Jannat Housing Society - Kahna', 'city': 'Lahore'},
    {'loc': 'Al-Qayyum Garden', 'city': 'Lahore'},
    {'loc': 'Al-Raheem Garden', 'city': 'Lahore'},
    {'loc': 'Al-Raziq Garden', 'city': 'Lahore'},
    {'loc': 'Al-Wahab Garden - Phase 1', 'city': 'Lahore'},
    {'loc': 'Alfalah Town', 'city': 'Lahore'},
    {'loc': 'Ali Alam Garden', 'city': 'Lahore'},
    {'loc': 'Ali Town', 'city': 'Lahore'},
    {'loc': 'Ali View Garden', 'city': 'Lahore'},
    {'loc': 'Ali View Park', 'city': 'Lahore'},
    {'loc': 'Allama Iqbal Intl Airport', 'city': 'Lahore'},
    {'loc': 'Allama Iqbal Road', 'city': 'Lahore'},
    {'loc': 'Allama Iqbal Town', 'city': 'Lahore'},
    {'loc': 'Altaf Colony', 'city': 'Lahore'},
    {'loc': 'Aman Town', 'city': 'Lahore'},
    {'loc': 'Ameen Park', 'city': 'Lahore'},
    {'loc': 'Amina Park', 'city': 'Lahore'},
    {'loc': 'Anarkali', 'city': 'Lahore'},
    {'loc': 'Angoori Bagh Scheme 1', 'city': 'Lahore'},
    {'loc': 'Architects Engineers Housing Society', 'city': 'Lahore'},
    {'loc': 'Arya Nagar', 'city': 'Lahore'},
    {'loc': 'Ashiana-e-Quaid Housing Scheme', 'city': 'Lahore'},
    {'loc': 'Ashraf Garden', 'city': 'Lahore'},
    {'loc': 'Ashrafi Town', 'city': 'Lahore'},
    {'loc': 'Asif Colony', 'city': 'Lahore'},
    {'loc': 'Asif Town', 'city': 'Lahore'},
    {'loc': 'Asim Town', 'city': 'Lahore'},
    {'loc': 'Askari', 'city': 'Lahore'},
    {'loc': 'Atari Saroba', 'city': 'Lahore'},
    {'loc': 'Audit & Accounts Housing Society', 'city': 'Lahore'},
    {'loc': 'Awan Town', 'city': 'Lahore'},
    {'loc': 'Awasia Housing Society', 'city': 'Lahore'},
    {'loc': 'Azadi Chowk', 'city': 'Lahore'},
    {'loc': 'Azam Cloth Market', 'city': 'Lahore'},
    {'loc': 'Azam Gardens', 'city': 'Lahore'},
    {'loc': 'BOR - Board of Revenue Housing Society', 'city': 'Lahore'},
    {'loc': 'BRB Canal Road', 'city': 'Lahore'},
    {'loc': 'Babu Sabu', 'city': 'Lahore'},
    {'loc': 'Badami Bagh', 'city': 'Lahore'},
    {'loc': 'Bagarian', 'city': 'Lahore'},
    {'loc': 'Bagh Gul Begum', 'city': 'Lahore'},
    {'loc': 'Baghban Pura Housing Scheme', 'city': 'Lahore'},
    {'loc': 'Baghbanpura', 'city': 'Lahore'},
    {'loc': 'Bahadurabad', 'city': 'Lahore'},
    {'loc': 'Bahar Colony', 'city': 'Lahore'},
    {'loc': 'Bahar Shah Road', 'city': 'Lahore'},
    {'loc': 'Bahria Education & Medical City', 'city': 'Lahore'},
    {'loc': 'Bahria Nasheman', 'city': 'Lahore'},
    {'loc': 'Bahria Orchard', 'city': 'Lahore'},
    {'loc': 'Bahria Town', 'city': 'Lahore'},
    {'loc': 'Band Road', 'city': 'Lahore'},
    {'loc': 'Bandian Wala', 'city': 'Lahore'},
    {'loc': 'Bankers Avenue Cooperative Housing Society', 'city': 'Lahore'},
    {'loc': 'Bankers Co-operative Housing Society', 'city': 'Lahore'},
    {'loc': 'Bankers Town', 'city': 'Lahore'},
    {'loc': 'Batapur', 'city': 'Lahore'},
    {'loc': 'Beacon House Society', 'city': 'Lahore'},
    {'loc': 'Beadon Road', 'city': 'Lahore'},
    {'loc': 'Bedian Road', 'city': 'Lahore'},
    {'loc': 'Begampura', 'city': 'Lahore'},
    {'loc': 'Begum Kot', 'city': 'Lahore'},
    {'loc': 'Bhagatpura', 'city': 'Lahore'},
    {'loc': 'Bhaini Road', 'city': 'Lahore'},
    {'loc': 'Bhasin', 'city': 'Lahore'},
    {'loc': 'Bhatta Chowk', 'city': 'Lahore'},
    {'loc': 'Bhatti Colony', 'city': 'Lahore'},
    {'loc': 'Bhogiwal', 'city': 'Lahore'},
    {'loc': 'Bhogiwal Road', 'city': 'Lahore'},
    {'loc': 'Bilal Gunj', 'city': 'Lahore'},
    {'loc': 'Brandreth Road', 'city': 'Lahore'},
    {'loc': 'Canal Bank Housing Scheme', 'city': 'Lahore'},
    {'loc': 'Canal Burg', 'city': 'Lahore'},
    {'loc': 'Canal Fort II', 'city': 'Lahore'},
    {'loc': 'Canal Garden', 'city': 'Lahore'},
    {'loc': 'Canal View', 'city': 'Lahore'},
    {'loc': 'Canalberg Housing Society', 'city': 'Lahore'},
    {'loc': 'Cantt', 'city': 'Lahore'},
    {'loc': 'Cantt View Society', 'city': 'Lahore'},
    {'loc': 'Captain Jamal Road', 'city': 'Lahore'},
    {'loc': 'Cavalry Extension', 'city': 'Lahore'},
    {'loc': 'Cavalry Ground', 'city': 'Lahore'},
    {'loc': 'Central Park Housing Scheme', 'city': 'Lahore'},
    {'loc': 'Chah Miran', 'city': 'Lahore'},
    {'loc': 'Chaman Park', 'city': 'Lahore'},
    {'loc': 'Chauburji', 'city': 'Lahore'},
    {'loc': 'Chauburji Chowk', 'city': 'Lahore'},
    {'loc': 'Chauburji Park Road', 'city': 'Lahore'},
    {'loc': 'Chaudhary Colony', 'city': 'Lahore'},
    {'loc': 'Chaudhary Park', 'city': 'Lahore'},
    {'loc': 'Chhapa', 'city': 'Lahore'},
    {'loc': 'China Scheme', 'city': 'Lahore'},
    {'loc': 'Chinar Bagh', 'city': 'Lahore'},
    {'loc': 'Chinar Court', 'city': 'Lahore'},
    {'loc': 'Chohan Road', 'city': 'Lahore'},
    {'loc': 'Chungi Amar Sadhu', 'city': 'Lahore'},
    {'loc': 'Circular Road', 'city': 'Lahore'},
    {'loc': 'Civil Defence', 'city': 'Lahore'},
    {'loc': 'Clifton Colony', 'city': 'Lahore'},
    {'loc': 'College Road', 'city': 'Lahore'},
    {'loc': 'Cooper Road', 'city': 'Lahore'},
    {'loc': 'Cricketer Villas', 'city': 'Lahore'},
    {'loc': 'DHA 11 Rahbar', 'city': 'Lahore'},
    {'loc': 'DHA City', 'city': 'Lahore'},
    {'loc': 'DHA Defence', 'city': 'Lahore'},
    {'loc': 'Daroghewala', 'city': 'Lahore'},
    {'loc': 'Dars Baray Mian', 'city': 'Lahore'},
    {'loc': 'Data Ganj Bakhsh Town', 'city': 'Lahore'},
    {'loc': 'Davis Road', 'city': 'Lahore'},
    {'loc': 'Defence Fort', 'city': 'Lahore'},
    {'loc': 'Defence Garden', 'city': 'Lahore'},
    {'loc': 'Defence Road', 'city': 'Lahore'},
    {'loc': 'Dharampura', 'city': 'Lahore'},
    {'loc': 'Dholanwal', 'city': 'Lahore'},
    {'loc': 'Divine Gardens', 'city': 'Lahore'},
    {'loc': 'Divine Homes', 'city': 'Lahore'},
    {'loc': 'Doctors Housing Society', 'city': 'Lahore'},
    {'loc': 'Dogech', 'city': 'Lahore'},
    {'loc': 'Dream Avenue Lahore', 'city': 'Lahore'},
    {'loc': 'Dream Villas', 'city': 'Lahore'},
    {'loc': 'Dubai Town', 'city': 'Lahore'},
    {'loc': 'Dubban Pura', 'city': 'Lahore'},
    {'loc': 'EME Society', 'city': 'Lahore'},
    {'loc': 'Eden', 'city': 'Lahore'},
    {'loc': 'Eden Avenue Extension', 'city': 'Lahore'},
    {'loc': 'Eden Park', 'city': 'Lahore'},
    {'loc': 'Eden Villas', 'city': 'Lahore'},
    {'loc': 'Education Town', 'city': 'Lahore'},
    {'loc': 'Elite Town', 'city': 'Lahore'},
    {'loc': 'Empress Road', 'city': 'Lahore'},
    {'loc': 'Excise & Taxation Housing Scheme', 'city': 'Lahore'},
    {'loc': 'Expo Avenue Society', 'city': 'Lahore'},
    {'loc': 'Faisal Town', 'city': 'Lahore'},
    {'loc': 'Faiz Bagh', 'city': 'Lahore'},
    {'loc': 'Farid Court Road', 'city': 'Lahore'},
    {'loc': 'Farooq Avenue', 'city': 'Lahore'},
    {'loc': 'Farooq Colony', 'city': 'Lahore'},
    {'loc': 'Fateh Garh', 'city': 'Lahore'},
    {'loc': 'Fateh Villas', 'city': 'Lahore'},
    {'loc': 'Fazaia Housing Scheme', 'city': 'Lahore'},
    {'loc': 'Ferozepur Road', 'city': 'Lahore'},
    {'loc': 'Ferozewala', 'city': 'Lahore'},
    {'loc': 'Formanites Housing Scheme', 'city': 'Lahore'},
    {'loc': 'GCP Housing Scheme', 'city': 'Lahore'},
    {'loc': 'GOR', 'city': 'Lahore'},
    {'loc': 'GT Road', 'city': 'Lahore'},
    {'loc': 'Gaddafi Stadium', 'city': 'Lahore'},
    {'loc': 'Gajju Matah', 'city': 'Lahore'},
    {'loc': 'Garden Town', 'city': 'Lahore'},
    {'loc': 'Garhi Shahu', 'city': 'Lahore'},
    {'loc': 'Garrison Homes', 'city': 'Lahore'},
    {'loc': 'Gawalmandi', 'city': 'Lahore'},
    {'loc': 'Ghaziabad', 'city': 'Lahore'},
    {'loc': 'Ghous Garden', 'city': 'Lahore'},
    {'loc': 'Gohawa', 'city': 'Lahore'},
    {'loc': 'Gold Land Garden', 'city': 'Lahore'},
    {'loc': 'Gosha-e-Ahbab', 'city': 'Lahore'},
    {'loc': 'Government Employees Cooperative Housing Society ', 'city': 'Lahore'},
    {'loc': 'Government Transport Headquarters Cooperative Housing Society', 'city': 'Lahore'},
    {'loc': 'Grand Avenues Housing Scheme', 'city': 'Lahore'},
    {'loc': 'Green Acres Housing Society', 'city': 'Lahore'},
    {'loc': 'Green Cap Housing Society', 'city': 'Lahore'},
    {'loc': 'Green City', 'city': 'Lahore'},
    {'loc': 'Green Fort', 'city': 'Lahore'},
    {'loc': 'Green Park', 'city': 'Lahore'},
    {'loc': 'Green Park Society', 'city': 'Lahore'},
    {'loc': 'Green Town Sector D2', 'city': 'Lahore'},
    {'loc': 'Green Villas', 'city': 'Lahore'},
    {'loc': 'Gujjar Colony', 'city': 'Lahore'},
    {'loc': 'Gul Colony', 'city': 'Lahore'},
    {'loc': 'Gul Kali', 'city': 'Lahore'},
    {'loc': 'Gul-e-Damin', 'city': 'Lahore'},
    {'loc': 'Gulbahar Colony', 'city': 'Lahore'},
    {'loc': 'Gulbahar Park', 'city': 'Lahore'},
    {'loc': 'Gulberg', 'city': 'Lahore'},
    {'loc': 'Guldasht Town', 'city': 'Lahore'},
    {'loc': 'Gulfishan Colony', 'city': 'Lahore'},
    {'loc': 'Gulfishan Town', 'city': 'Lahore'},
    {'loc': 'Gulistan Colony', 'city': 'Lahore'},
    {'loc': 'Gulshan Colony', 'city': 'Lahore'},
    {'loc': 'Gulshan Farooq Scheme', 'city': 'Lahore'},
    {'loc': 'Gulshan Park', 'city': 'Lahore'},
    {'loc': 'Gulshan-E-Anwar', 'city': 'Lahore'},
    {'loc': 'Gulshan-E-Mustafa Housing Society', 'city': 'Lahore'},
    {'loc': 'Gulshan-e-Ahbab', 'city': 'Lahore'},
    {'loc': 'Gulshan-e-Lahore', 'city': 'Lahore'},
    {'loc': 'Gulshan-e-Ravi', 'city': 'Lahore'},
    {'loc': 'Gulshan-e-Sardar Housing Scheme', 'city': 'Lahore'},
    {'loc': 'Gulshan-e-Shalimar Housing Scheme', 'city': 'Lahore'},
    {'loc': 'Gulshan-e-Yaseen Housing Society', 'city': 'Lahore'},
    {'loc': 'Gulzar E Ahbab Society', 'city': 'Lahore'},
    {'loc': 'HBFC Housing Society', 'city': 'Lahore'},
    {'loc': 'Habib Homes', 'city': 'Lahore'},
    {'loc': 'Habibullah Road', 'city': 'Lahore'},
    {'loc': 'Haji Park Housing Scheme', 'city': 'Lahore'},
    {'loc': 'Hajvery Housing Scheme', 'city': 'Lahore'},
    {'loc': 'Hakim Town', 'city': 'Lahore'},
    {'loc': 'Hall Road', 'city': 'Lahore'},
    {'loc': 'Hameedpura', 'city': 'Lahore'},
    {'loc': 'Hamza Town', 'city': 'Lahore'},
    {'loc': 'Hanif Park Harbanspura', 'city': 'Lahore'},
    {'loc': 'Hanjarwal', 'city': 'Lahore'},
    {'loc': 'Harbanspura', 'city': 'Lahore'},
    {'loc': 'Harbanspura Road', 'city': 'Lahore'},
    {'loc': 'Hassan Town', 'city': 'Lahore'},
    {'loc': 'Hayderabad', 'city': 'Lahore'},
    {'loc': 'Heir', 'city': 'Lahore'},
    {'loc': 'Highcourt Society', 'city': 'Lahore'},
    {'loc': 'IBL Housing Scheme', 'city': 'Lahore'},
    {'loc': 'IEP Engineers Town', 'city': 'Lahore'},
    {'loc': 'Ibrahim Colony', 'city': 'Lahore'},
    {'loc': 'Ichhra', 'city': 'Lahore'},
    {'loc': 'Icon Valley', 'city': 'Lahore'},
    {'loc': 'Ideal Homes', 'city': 'Lahore'},
    {'loc': 'Immad Garden Housing Scheme', 'city': 'Lahore'},
    {'loc': 'Infantry Road', 'city': 'Lahore'},
    {'loc': 'Inmol Society', 'city': 'Lahore'},
    {'loc': 'Iqbal Avenue', 'city': 'Lahore'},
    {'loc': 'Iqbal Park', 'city': 'Lahore'},
    {'loc': 'Irrigation Cooperative Housing Society', 'city': 'Lahore'},
    {'loc': 'Islam Nagar', 'city': 'Lahore'},
    {'loc': 'Islamabad Colony', 'city': 'Lahore'},
    {'loc': 'Islamia Park', 'city': 'Lahore'},
    {'loc': 'Islampura', 'city': 'Lahore'},
    {'loc': 'Ismail Town', 'city': 'Lahore'},
    {'loc': 'Ittehad Park', 'city': 'Lahore'},
    {'loc': 'Ittifaq Town', 'city': 'Lahore'},
    {'loc': 'Izmir Town', 'city': 'Lahore'},
    {'loc': 'Jaffar Town', 'city': 'Lahore'},
    {'loc': 'Jaffaria Colony', 'city': 'Lahore'},
    {'loc': 'Jail Road', 'city': 'Lahore'},
    {'loc': 'Jalal Colony', 'city': 'Lahore'},
    {'loc': 'Jallo', 'city': 'Lahore'},
    {'loc': 'Jallo Park Road', 'city': 'Lahore'},
    {'loc': 'Jamal Homes', 'city': 'Lahore'},
    {'loc': 'Jamil Town', 'city': 'Lahore'},
    {'loc': 'Jan Muhammad Road', 'city': 'Lahore'},
    {'loc': 'Jati Umra Road', 'city': 'Lahore'},
    {'loc': 'Javed Colony - Ghazi Road', 'city': 'Lahore'},
    {'loc': 'Jia Baga Road', 'city': 'Lahore'},
    {'loc': 'Jinnah Colony', 'city': 'Lahore'},
    {'loc': 'Johar Town', 'city': 'Lahore'},
    {'loc': 'Jora Pull', 'city': 'Lahore'},
    {'loc': 'Jubilee Town', 'city': 'Lahore'},
    {'loc': 'Judicial Colony', 'city': 'Lahore'},
    {'loc': 'Kacha Ferozepur Road', 'city': 'Lahore'},
    {'loc': 'Kacha Jail Road', 'city': 'Lahore'},
    {'loc': 'Kacha Lawrence Road', 'city': 'Lahore'},
    {'loc': 'Kacha Road', 'city': 'Lahore'},
    {'loc': 'Kachupura', 'city': 'Lahore'},
    {'loc': 'Kahna', 'city': 'Lahore'},
    {'loc': 'Kahna Kacha', 'city': 'Lahore'},
    {'loc': 'Kala Khatai Road', 'city': 'Lahore'},
    {'loc': 'Kalma Chowk', 'city': 'Lahore'},
    {'loc': 'Kamahan Road', 'city': 'Lahore'},
    {'loc': 'Karbath', 'city': 'Lahore'},
    {'loc': 'Karim Park', 'city': 'Lahore'},
    {'loc': 'Katar Bund Road', 'city': 'Lahore'},
    {'loc': 'Kausar Colony', 'city': 'Lahore'},
    {'loc': 'Keer Khurd', 'city': 'Lahore'},
    {'loc': 'Khaira', 'city': 'Lahore'},
    {'loc': 'Khana Kacha Road', 'city': 'Lahore'},
    {'loc': 'Kharak', 'city': 'Lahore'},
    {'loc': 'Khayaban-e-Amin', 'city': 'Lahore'},
    {'loc': 'Khayaban-e-Jinnah Road', 'city': 'Lahore'},
    {'loc': 'Khayaban-e-Quaid', 'city': 'Lahore'},
    {'loc': 'Khokhar Town', 'city': 'Lahore'},
    {'loc': 'Khursheed Alam Road', 'city': 'Lahore'},
    {'loc': 'Kot Araian', 'city': 'Lahore'},
    {'loc': 'Kot Khawaja Saeed', 'city': 'Lahore'},
    {'loc': 'Kot Lakhpat', 'city': 'Lahore'},
    {'loc': 'Kotli Abdur Rahman', 'city': 'Lahore'},
    {'loc': 'Krishan Nagar', 'city': 'Lahore'},
    {'loc': 'LDA Avenue', 'city': 'Lahore'},
    {'loc': 'LDA Road', 'city': 'Lahore'},
    {'loc': 'Labor Colony', 'city': 'Lahore'},
    {'loc': 'Lahore - Islamabad Motorway', 'city': 'Lahore'},
    {'loc': 'Lahore - Jaranwala Road', 'city': 'Lahore'},
    {'loc': 'Lahore - Kasur Road', 'city': 'Lahore'},
    {'loc': 'Lahore Canal Bank Cooperative Housing Society', 'city': 'Lahore'},
    {'loc': 'Lahore Medical Housing Society', 'city': 'Lahore'},
    {'loc': 'Lahore Motorway City', 'city': 'Lahore'},
    {'loc': 'Lahore Press Club Housing Scheme', 'city': 'Lahore'},
    {'loc': 'Lahore Railway Station Road', 'city': 'Lahore'},
    {'loc': 'Lahore Villas', 'city': 'Lahore'},
    {'loc': 'Lakhodher', 'city': 'Lahore'},
    {'loc': 'Lakshmi Chowk', 'city': 'Lahore'},
    {'loc': 'Lalazaar Garden', 'city': 'Lahore'},
    {'loc': 'Lalazar', 'city': 'Lahore'},
    {'loc': 'Land Breeze Housing Society', 'city': 'Lahore'},
    {'loc': 'Lawrence Road', 'city': 'Lahore'},
    {'loc': 'Liaquatabad', 'city': 'Lahore'},
    {'loc': 'Lytton Road', 'city': 'Lahore'},
    {'loc': 'MET 2', 'city': 'Lahore'},
    {'loc': 'Madar-e-Millat Road', 'city': 'Lahore'},
    {'loc': 'Madina Colony', 'city': 'Lahore'},
    {'loc': 'Madina Homes', 'city': 'Lahore'},
    {'loc': 'Madina Town', 'city': 'Lahore'},
    {'loc': 'Main Canal Bank Road', 'city': 'Lahore'},
    {'loc': 'Makkah Colony', 'city': 'Lahore'},
    {'loc': 'Makki Complex', 'city': 'Lahore'},
    {'loc': 'Malik Park', 'city': 'Lahore'},
    {'loc': 'Mall Road', 'city': 'Lahore'},
    {'loc': 'Manawan', 'city': 'Lahore'},
    {'loc': 'Manga - Raiwind Road', 'city': 'Lahore'},
    {'loc': 'Manga Mandi', 'city': 'Lahore'},
    {'loc': 'Manhala Road', 'city': 'Lahore'},
    {'loc': 'Mansoora Homes', 'city': 'Lahore'},
    {'loc': 'Mansoorah', 'city': 'Lahore'},
    {'loc': 'Manzoor Colony', 'city': 'Lahore'},
    {'loc': 'Marghzar Officers Colony', 'city': 'Lahore'},
    {'loc': 'Maryam Town', 'city': 'Lahore'},
    {'loc': 'Mason Road', 'city': 'Lahore'},
    {'loc': 'Mateen Avenue', 'city': 'Lahore'},
    {'loc': 'Mateen Garden', 'city': 'Lahore'},
    {'loc': 'Maulana Shaukat Ali Road', 'city': 'Lahore'},
    {'loc': 'McLeod Road', 'city': 'Lahore'},
    {'loc': 'Mehar Fayaz Colony', 'city': 'Lahore'},
    {'loc': 'Meharpura', 'city': 'Lahore'},
    {'loc': 'Mehmood Booti', 'city': 'Lahore'},
    {'loc': 'Mehrabad', 'city': 'Lahore'},
    {'loc': 'Meraj Park', 'city': 'Lahore'},
    {'loc': 'Mian Amiruddin Park', 'city': 'Lahore'},
    {'loc': 'Mian Aziz Garden', 'city': 'Lahore'},
    {'loc': 'Mian Mir Colony', 'city': 'Lahore'},
    {'loc': 'Military Accounts Housing Society', 'city': 'Lahore'},
    {'loc': 'Millat Road', 'city': 'Lahore'},
    {'loc': 'Misri Shah', 'city': 'Lahore'},
    {'loc': 'Model Colony', 'city': 'Lahore'},
    {'loc': 'Model Town', 'city': 'Lahore'},
    {'loc': 'Mohafiz Town', 'city': 'Lahore'},
    {'loc': 'Mohlanwal', 'city': 'Lahore'},
    {'loc': 'Mohlanwal Road', 'city': 'Lahore'},
    {'loc': 'Mohlanwal Scheme', 'city': 'Lahore'},
    {'loc': 'Mohni Road', 'city': 'Lahore'},
    {'loc': 'Mominpur', 'city': 'Lahore'},
    {'loc': 'Mominpura Road', 'city': 'Lahore'},
    {'loc': 'Montgomery Road', 'city': 'Lahore'},
    {'loc': 'Moon Colony', 'city': 'Lahore'},
    {'loc': 'Mozang', 'city': 'Lahore'},
    {'loc': 'Mubarak Town', 'city': 'Lahore'},
    {'loc': 'Mughalpura', 'city': 'Lahore'},
    {'loc': 'Multan Road', 'city': 'Lahore'},
    {'loc': 'Munir Garden', 'city': 'Lahore'},
    {'loc': 'Muslim Nagar Housing Scheme', 'city': 'Lahore'},
    {'loc': 'Muslim Town', 'city': 'Lahore'},
    {'loc': 'Mustafa Town', 'city': 'Lahore'},
    {'loc': 'Mustafabad Lalyani', 'city': 'Lahore'},
    {'loc': 'NFC 1', 'city': 'Lahore'},
    {'loc': 'Nabi Pura', 'city': 'Lahore'},
    {'loc': 'Nadeem Shaheed Road', 'city': 'Lahore'},
    {'loc': 'Nadeem Town', 'city': 'Lahore'},
    {'loc': 'Nadia Ghee Mill Chowk', 'city': 'Lahore'},
    {'loc': 'Nai Abadi Harbanspura', 'city': 'Lahore'},
    {'loc': 'Nain Sukh', 'city': 'Lahore'},
    {'loc': 'Nasheman-e-Iqbal', 'city': 'Lahore'},
    {'loc': 'Nasirabad', 'city': 'Lahore'},
    {'loc': 'National Town', 'city': 'Lahore'},
    {'loc': 'Nawab Town', 'city': 'Lahore'},
    {'loc': 'Nawaz Sharif Colony', 'city': 'Lahore'},
    {'loc': 'Naz Town', 'city': 'Lahore'},
    {'loc': 'Nazir Garden Society', 'city': 'Lahore'},
    {'loc': 'New Amir Town', 'city': 'Lahore'},
    {'loc': 'New Canal Park', 'city': 'Lahore'},
    {'loc': 'New Chauburji Park', 'city': 'Lahore'},
    {'loc': 'New Garden Town', 'city': 'Lahore'},
    {'loc': 'New Khan Colony', 'city': 'Lahore'},
    {'loc': 'New Lahore City', 'city': 'Lahore'},
    {'loc': 'New Muslim Town', 'city': 'Lahore'},
    {'loc': 'New Samanabad', 'city': 'Lahore'},
    {'loc': 'New Shah Kamal Colony', 'city': 'Lahore'},
    {'loc': 'New Super Town', 'city': 'Lahore'},
    {'loc': 'Nicholson Road', 'city': 'Lahore'},
    {'loc': 'Nisbat Road', 'city': 'Lahore'},
    {'loc': 'Nishat Colony', 'city': 'Lahore'},
    {'loc': 'Nishtar Colony', 'city': 'Lahore'},
    {'loc': 'Nizamabad', 'city': 'Lahore'},
    {'loc': 'Noor Jahan Road', 'city': 'Lahore'},
    {'loc': 'OPF Housing Scheme', 'city': 'Lahore'},
    {'loc': 'Officer Colony', 'city': 'Lahore'},
    {'loc': 'Outfall Road', 'city': 'Lahore'},
    {'loc': 'P & D Housing Society', 'city': 'Lahore'},
    {'loc': 'PASSCO Housing Society', 'city': 'Lahore'},
    {'loc': 'PCSIR Housing Scheme', 'city': 'Lahore'},
    {'loc': 'PCSIR Staff Colony', 'city': 'Lahore'},
    {'loc': 'PIA Housing Scheme', 'city': 'Lahore'},
    {'loc': 'PIA Main Boulevard', 'city': 'Lahore'},
    {'loc': 'Pak Arab Housing Society', 'city': 'Lahore'},
    {'loc': 'Pak Park', 'city': 'Lahore'},
    {'loc': 'Pakistan Medical Housing Society', 'city': 'Lahore'},
    {'loc': 'Pakki Thatti', 'city': 'Lahore'},
    {'loc': 'Palm Villas', 'city': 'Lahore'},
    {'loc': 'Paradise Homes Super Town', 'city': 'Lahore'},
    {'loc': 'Paragon City', 'city': 'Lahore'},
    {'loc': 'Park View City', 'city': 'Lahore'},
    {'loc': 'Peco Road', 'city': 'Lahore'},
    {'loc': 'Pir Naseer', 'city': 'Lahore'},
    {'loc': 'Poonch Road', 'city': 'Lahore'},
    {'loc': 'Prem Nagar', 'city': 'Lahore'},
    {'loc': 'Prime Homes 1', 'city': 'Lahore'},
    {'loc': 'Prime Homes 2', 'city': 'Lahore'},
    {'loc': 'Public Health Society', 'city': 'Lahore'},
    {'loc': 'Punjab Coop Housing Society', 'city': 'Lahore'},
    {'loc': 'Punjab Government Labor Colony', 'city': 'Lahore'},
    {'loc': 'Punjab Government Servant Housing Foundation', 'city': 'Lahore'},
    {'loc': 'Punjab Govt Employees Society', 'city': 'Lahore'},
    {'loc': 'Punjab Small Industries Colony', 'city': 'Lahore'},
    {'loc': 'Punjab University Employees Society', 'city': 'Lahore'},
    {'loc': 'Qadri Colony', 'city': 'Lahore'},
    {'loc': 'Qartaba Chowk', 'city': 'Lahore'},
    {'loc': 'Qasim Garden', 'city': 'Lahore'},
    {'loc': 'Qazi Town', 'city': 'Lahore'},
    {'loc': 'Qilla Gujjar Singh', 'city': 'Lahore'},
    {'loc': 'Quaid-e-Azam Industrial Estate', 'city': 'Lahore'},
    {'loc': 'Rail Town ', 'city': 'Lahore'},
    {'loc': 'Railway Officers Colony', 'city': 'Lahore'},
    {'loc': 'Raiwind Road', 'city': 'Lahore'},
    {'loc': 'Raj Garh', 'city': 'Lahore'},
    {'loc': 'Rajgarh Road', 'city': 'Lahore'},
    {'loc': 'Rajpoot Town', 'city': 'Lahore'},
    {'loc': 'Rana Town', 'city': 'Lahore'},
    {'loc': 'Rang Mahal', 'city': 'Lahore'},
    {'loc': 'Rasool Park', 'city': 'Lahore'},
    {'loc': 'Ravi Road', 'city': 'Lahore'},
    {'loc': 'Ravi Siphon Road', 'city': 'Lahore'},
    {'loc': 'Real Cottages', 'city': 'Lahore'},
    {'loc': 'Rehan Garden', 'city': 'Lahore'},
    {'loc': 'Rehman City - Phase 4', 'city': 'Lahore'},
    {'loc': 'Rehman City Phase 6', 'city': 'Lahore'},
    {'loc': 'Rehman Gardens', 'city': 'Lahore'},
    {'loc': 'Rehman Park', 'city': 'Lahore'},
    {'loc': 'Rehman Villas', 'city': 'Lahore'},
    {'loc': 'Rehmanpura ', 'city': 'Lahore'},
    {'loc': 'Rehmanpura ', 'city': 'Lahore'},
    {'loc': 'Rehmat Colony', 'city': 'Lahore'},
    {'loc': 'Revenue Society', 'city': 'Lahore'},
    {'loc': 'Rewaz Garden', 'city': 'Lahore'},
    {'loc': 'Rifle Range Road', 'city': 'Lahore'},
    {'loc': 'Ring Road', 'city': 'Lahore'},
    {'loc': 'River View Coop Housing Society', 'city': 'Lahore'},
    {'loc': 'Riwaz Garden', 'city': 'Lahore'},
    {'loc': 'Rizwan Garden Scheme', 'city': 'Lahore'},
    {'loc': 'Rohi Nala Road', 'city': 'Lahore'},
    {'loc': 'Royal Garden', 'city': 'Lahore'},
    {'loc': 'Royal Residencia', 'city': 'Lahore'},
    {'loc': 'Rustam Park', 'city': 'Lahore'},
    {'loc': 'Saadi Park', 'city': 'Lahore'},
    {'loc': 'Sabzazar Scheme', 'city': 'Lahore'},
    {'loc': 'Sadaat Town', 'city': 'Lahore'},
    {'loc': 'Safari Garden Housing Scheme', 'city': 'Lahore'},
    {'loc': 'Saggian', 'city': 'Lahore'},
    {'loc': 'Saggian Wala Bypass Road', 'city': 'Lahore'},
    {'loc': 'Sahafi Colony', 'city': 'Lahore'},
    {'loc': 'Saiden Shah Colony', 'city': 'Lahore'},
    {'loc': 'Saidpur', 'city': 'Lahore'},
    {'loc': 'Sajid Garden', 'city': 'Lahore'},
    {'loc': 'Salamatpura', 'city': 'Lahore'},
    {'loc': 'Salli Town', 'city': 'Lahore'},
    {'loc': 'Samanabad', 'city': 'Lahore'},
    {'loc': 'Samanzar Colony', 'city': 'Lahore'},
    {'loc': 'Sami Town', 'city': 'Lahore'},
    {'loc': 'Sanda', 'city': 'Lahore'},
    {'loc': 'Sanda Road', 'city': 'Lahore'},
    {'loc': 'Sant Nagar', 'city': 'Lahore'},
    {'loc': 'Saqib Town', 'city': 'Lahore'},
    {'loc': 'Saroba Gardens Housing Society', 'city': 'Lahore'},
    {'loc': 'Sarwar Town', 'city': 'Lahore'},
    {'loc': 'Shabbir Town', 'city': 'Lahore'},
    {'loc': 'Shadab Garden', 'city': 'Lahore'},
    {'loc': 'Shadbagh', 'city': 'Lahore'},
    {'loc': 'Shadipura', 'city': 'Lahore'},
    {'loc': 'Shadman', 'city': 'Lahore'},
    {'loc': 'Shadman Enclave', 'city': 'Lahore'},
    {'loc': 'Shah Di Khoi', 'city': 'Lahore'},
    {'loc': 'Shah Faisal Road', 'city': 'Lahore'},
    {'loc': 'Shah Jamal', 'city': 'Lahore'},
    {'loc': 'Shah Kamal Road', 'city': 'Lahore'},
    {'loc': 'Shah Khawar Town', 'city': 'Lahore'},
    {'loc': 'Shahdara', 'city': 'Lahore'},
    {'loc': 'Shahkam Chowk', 'city': 'Lahore'},
    {'loc': 'Shahpur Kanjra', 'city': 'Lahore'},
    {'loc': 'Shahtaj Colony', 'city': 'Lahore'},
    {'loc': 'Shalimar Housing Scheme', 'city': 'Lahore'},
    {'loc': 'Shalimar Link Road', 'city': 'Lahore'},
    {'loc': 'Shalimar Town', 'city': 'Lahore'},
    {'loc': 'Sham Nagar', 'city': 'Lahore'},
    {'loc': 'Shama Road', 'city': 'Lahore'},
    {'loc': 'Shams Colony', 'city': 'Lahore'},
    {'loc': 'Shanghai Road', 'city': 'Lahore'},
    {'loc': 'Sharaqpur Road', 'city': 'Lahore'},
    {'loc': 'Sheikhupura Road', 'city': 'Lahore'},
    {'loc': 'Sher Ali Road', 'city': 'Lahore'},
    {'loc': 'Sher Shah Road', 'city': 'Lahore'},
    {'loc': 'Shera Kot', 'city': 'Lahore'},
    {'loc': 'Sheraz Town', 'city': 'Lahore'},
    {'loc': 'Sheraz Villas', 'city': 'Lahore'},
    {'loc': 'Shershah Colony - Ichra', 'city': 'Lahore'},
    {'loc': 'Shershah Colony - Raiwind Road', 'city': 'Lahore'},
    {'loc': 'Sherwani Town Housing Scheme', 'city': 'Lahore'},
    {'loc': 'Shoukat Town', 'city': 'Lahore'},
    {'loc': 'Shuja Road', 'city': 'Lahore'},
    {'loc': 'Siddiqia Colony', 'city': 'Lahore'},
    {'loc': 'Siddiqia Society ', 'city': 'Lahore'},
    {'loc': 'Singhpura', 'city': 'Lahore'},
    {'loc': 'Sitara Colony', 'city': 'Lahore'},
    {'loc': 'Sodiwal', 'city': 'Lahore'},
    {'loc': 'Sozo Town', 'city': 'Lahore'},
    {'loc': 'State Life Housing Society', 'city': 'Lahore'},
    {'loc': 'Sue-e-Asal', 'city': 'Lahore'},
    {'loc': 'Sue-e-Asal Road', 'city': 'Lahore'},
    {'loc': 'Sufiabad', 'city': 'Lahore'},
    {'loc': 'Sui Gas Employees Cooperative Housing Society', 'city': 'Lahore'},
    {'loc': 'Sui Gas Housing Society', 'city': 'Lahore'},
    {'loc': 'Sukh Chayn Gardens', 'city': 'Lahore'},
    {'loc': 'Sultan Ahmed Road', 'city': 'Lahore'},
    {'loc': 'Sultan Colony', 'city': 'Lahore'},
    {'loc': 'Sultan Pura', 'city': 'Lahore'},
    {'loc': 'Sultan Town', 'city': 'Lahore'},
    {'loc': 'Sultanke', 'city': 'Lahore'},
    {'loc': 'Sundar Road', 'city': 'Lahore'},
    {'loc': 'Sunflower Housing Society', 'city': 'Lahore'},
    {'loc': 'Sunfort Gardens', 'city': 'Lahore'},
    {'loc': 'Sunny Park', 'city': 'Lahore'},
    {'loc': 'Super Town', 'city': 'Lahore'},
    {'loc': 'Supreme Villas', 'city': 'Lahore'},
    {'loc': 'Swami Nagar', 'city': 'Lahore'},
    {'loc': 'T & T Aabpara Housing Society', 'city': 'Lahore'},
    {'loc': 'TECH Society', 'city': 'Lahore'},
    {'loc': 'TIP Housing Society', 'city': 'Lahore'},
    {'loc': 'Taj Bagh Scheme', 'city': 'Lahore'},
    {'loc': 'Tajpura', 'city': 'Lahore'},
    {'loc': 'Tariq Colony', 'city': 'Lahore'},
    {'loc': 'Tariq Gardens', 'city': 'Lahore'},
    {'loc': 'Tariq Ismail Road', 'city': 'Lahore'},
    {'loc': 'Temple Road', 'city': 'Lahore'},
    {'loc': 'Thethar', 'city': 'Lahore'},
    {'loc': 'Thokar Niaz Baig', 'city': 'Lahore'},
    {'loc': 'Toheed Park', 'city': 'Lahore'},
    {'loc': 'Township', 'city': 'Lahore'},
    {'loc': 'Tricon Village', 'city': 'Lahore'},
    {'loc': 'UBL Housing Society', 'city': 'Lahore'},
    {'loc': 'UET Housing Society', 'city': 'Lahore'},
    {'loc': 'Upper Mall', 'city': 'Lahore'},
    {'loc': 'Usman Park', 'city': 'Lahore'},
    {'loc': 'Usmania Colony', 'city': 'Lahore'},
    {'loc': 'Valencia Housing Society', 'city': 'Lahore'},
    {'loc': 'Venus Housing Scheme', 'city': 'Lahore'},
    {'loc': 'Vital Homes Housing Scheme', 'city': 'Lahore'},
    {'loc': 'Wafaqi Colony', 'city': 'Lahore'},
    {'loc': 'Wagha Town', 'city': 'Lahore'},
    {'loc': 'Wahdat Colony', 'city': 'Lahore'},
    {'loc': 'Wahdat Road', 'city': 'Lahore'},
    {'loc': 'Walled City', 'city': 'Lahore'},
    {'loc': 'Walton Railway Officers Colony', 'city': 'Lahore'},
    {'loc': 'Walton Road', 'city': 'Lahore'},
    {'loc': 'Wapda Town', 'city': 'Lahore'},
    {'loc': 'Waris Colony', 'city': 'Lahore'},
    {'loc': 'Waris Road', 'city': 'Lahore'},
    {'loc': 'Wassan Pura Scheme No. 2', 'city': 'Lahore'},
    {'loc': 'Wassanpura', 'city': 'Lahore'},
    {'loc': 'West Wood Housing Society', 'city': 'Lahore'},
    {'loc': 'Women Housing Society', 'city': 'Lahore'},
    {'loc': 'Yasrab Colony', 'city': 'Lahore'},
    {'loc': 'Yazdani Road', 'city': 'Lahore'},
    {'loc': 'Youhanabad', 'city': 'Lahore'},
    {'loc': 'Zafar Colony', 'city': 'Lahore'},
    {'loc': 'Zaheer Villas', 'city': 'Lahore'},
    {'loc': 'Zaitoon Colony', 'city': 'Lahore'},
    {'loc': 'Zam Zam City', 'city': 'Lahore'},
    {'loc': 'Zaman Colony', 'city': 'Lahore'},
    {'loc': 'Zaman Park', 'city': 'Lahore'},
    {'loc': 'Zubaida Park', 'city': 'Lahore'},
    {'loc': '7th Avenue', 'city': 'Islamabad'},
    {'loc': '9th Avenue', 'city': 'Islamabad'},
    {'loc': 'AGHOSH', 'city': 'Islamabad'},
    {'loc': 'Abdullah Garden', 'city': 'Islamabad'},
    {'loc': 'Airport Avenue Housing Society', 'city': 'Islamabad'},
    {'loc': 'Airport Enclave', 'city': 'Islamabad'},
    {'loc': 'Aiza Garden', 'city': 'Islamabad'},
    {'loc': 'Al Huda Town', 'city': 'Islamabad'},
    {'loc': 'Al Qaim Town', 'city': 'Islamabad'},
    {'loc': 'Ali Pur', 'city': 'Islamabad'},
    {'loc': 'Alipur Farash', 'city': 'Islamabad'},
    {'loc': 'Angoori Road', 'city': 'Islamabad'},
    {'loc': 'Arsalan Town', 'city': 'Islamabad'},
    {'loc': 'Athal', 'city': 'Islamabad'},
    {'loc': 'Atomic Energy Employee Society', 'city': 'Islamabad'},
    {'loc': 'B-17', 'city': 'Islamabad'},
    {'loc': 'Bahria Town', 'city': 'Islamabad'},
    {'loc': 'Bani Gala', 'city': 'Islamabad'},
    {'loc': 'Bhara kahu', 'city': 'Islamabad'},
    {'loc': 'Blue Area', 'city': 'Islamabad'},
    {'loc': 'Bokra Road', 'city': 'Islamabad'},
    {'loc': 'Burma Town', 'city': 'Islamabad'},
    {'loc': 'C-18', 'city': 'Islamabad'},
    {'loc': 'C-19', 'city': 'Islamabad'},
    {'loc': 'CBR Town', 'city': 'Islamabad'},
    {'loc': 'Capital Enclave', 'city': 'Islamabad'},
    {'loc': 'Chak Shahzad', 'city': 'Islamabad'},
    {'loc': 'Chatha Bakhtawar', 'city': 'Islamabad'},
    {'loc': 'Chattar', 'city': 'Islamabad'},
    {'loc': 'Constitution Avenue', 'city': 'Islamabad'},
    {'loc': 'D-12', 'city': 'Islamabad'},
    {'loc': 'D-13', 'city': 'Islamabad'},
    {'loc': 'D-14', 'city': 'Islamabad'},
    {'loc': 'D-16', 'city': 'Islamabad'},
    {'loc': 'D-17', 'city': 'Islamabad'},
    {'loc': 'D-18', 'city': 'Islamabad'},
    {'loc': 'DHA Defence', 'city': 'Islamabad'},
    {'loc': 'Diplomatic Enclave', 'city': 'Islamabad'},
    {'loc': 'E-11', 'city': 'Islamabad'},
    {'loc': 'E-13', 'city': 'Islamabad'},
    {'loc': 'E-14', 'city': 'Islamabad'},
    {'loc': 'E-15', 'city': 'Islamabad'},
    {'loc': 'E-16', 'city': 'Islamabad'},
    {'loc': 'E-17', 'city': 'Islamabad'},
    {'loc': 'E-18', 'city': 'Islamabad'},
    {'loc': 'E-7', 'city': 'Islamabad'},
    {'loc': 'Eden Life Islamabad', 'city': 'Islamabad'},
    {'loc': 'Emaar Canyon Views', 'city': 'Islamabad'},
    {'loc': 'F-10', 'city': 'Islamabad'},
    {'loc': 'F-11', 'city': 'Islamabad'},
    {'loc': 'F-15', 'city': 'Islamabad'},
    {'loc': 'F-17', 'city': 'Islamabad'},
    {'loc': 'F-6', 'city': 'Islamabad'},
    {'loc': 'F-7', 'city': 'Islamabad'},
    {'loc': 'F-8', 'city': 'Islamabad'},
    {'loc': 'FECHS', 'city': 'Islamabad'},
    {'loc': 'Faisal Town - F-18', 'city': 'Islamabad'},
    {'loc': 'Fateh Jang Road', 'city': 'Islamabad'},
    {'loc': 'Federal Government Employees Housing Foundation', 'city': 'Islamabad'},
    {'loc': 'Frash Town', 'city': 'Islamabad'},
    {'loc': 'G-10', 'city': 'Islamabad'},
    {'loc': 'G-11', 'city': 'Islamabad'},
    {'loc': 'G-12', 'city': 'Islamabad'},
    {'loc': 'G-13', 'city': 'Islamabad'},
    {'loc': 'G-14', 'city': 'Islamabad'},
    {'loc': 'G-15', 'city': 'Islamabad'},
    {'loc': 'G-16', 'city': 'Islamabad'},
    {'loc': 'G-17', 'city': 'Islamabad'},
    {'loc': 'G-6', 'city': 'Islamabad'},
    {'loc': 'G-7', 'city': 'Islamabad'},
    {'loc': 'G-8', 'city': 'Islamabad'},
    {'loc': 'G-9', 'city': 'Islamabad'},
    {'loc': 'GT Road', 'city': 'Islamabad'},
    {'loc': 'Gandhara City', 'city': 'Islamabad'},
    {'loc': 'Garden Town', 'city': 'Islamabad'},
    {'loc': 'Ghauri Town', 'city': 'Islamabad'},
    {'loc': 'Golra Mor', 'city': 'Islamabad'},
    {'loc': 'Golra Road', 'city': 'Islamabad'},
    {'loc': 'Green Avenue', 'city': 'Islamabad'},
    {'loc': 'Green Hills Housing Scheme', 'city': 'Islamabad'},
    {'loc': 'Gulberg', 'city': 'Islamabad'},
    {'loc': 'Gulf Residencia', 'city': 'Islamabad'},
    {'loc': 'Gulshan-e-Khudadad', 'city': 'Islamabad'},
    {'loc': 'H-11', 'city': 'Islamabad'},
    {'loc': 'H-12', 'city': 'Islamabad'},
    {'loc': 'H-13', 'city': 'Islamabad'},
    {'loc': 'H-15', 'city': 'Islamabad'},
    {'loc': 'H-9', 'city': 'Islamabad'},
    {'loc': 'I-10', 'city': 'Islamabad'},
    {'loc': 'I-11', 'city': 'Islamabad'},
    {'loc': 'I-12', 'city': 'Islamabad'},
    {'loc': 'I-13', 'city': 'Islamabad'},
    {'loc': 'I-14', 'city': 'Islamabad'},
    {'loc': 'I-16', 'city': 'Islamabad'},
    {'loc': 'I-8', 'city': 'Islamabad'},
    {'loc': 'I-9', 'city': 'Islamabad'},
    {'loc': 'IJP Road', 'city': 'Islamabad'},
    {'loc': 'Ibn-e-Sina Road', 'city': 'Islamabad'},
    {'loc': 'Iqbal Town', 'city': 'Islamabad'},
    {'loc': 'Islamabad - Murree Expressway', 'city': 'Islamabad'},
    {'loc': 'Islamabad - Peshawar Motorway', 'city': 'Islamabad'},
    {'loc': 'Islamabad Expressway', 'city': 'Islamabad'},
    {'loc': 'Islamabad Garden', 'city': 'Islamabad'},
    {'loc': 'Islamabad Golf City', 'city': 'Islamabad'},
    {'loc': 'Islamabad Highway', 'city': 'Islamabad'},
    {'loc': 'Ittefaq Town', 'city': 'Islamabad'},
    {'loc': 'J and K Zone 5', 'city': 'Islamabad'},
    {'loc': 'Jagiot Road', 'city': 'Islamabad'},
    {'loc': 'Jandala Road', 'city': 'Islamabad'},
    {'loc': 'Jeddah Town', 'city': 'Islamabad'},
    {'loc': 'Jhang Syedan', 'city': 'Islamabad'},
    {'loc': 'Jhangi Syedan', 'city': 'Islamabad'},
    {'loc': 'Jinnah Avenue', 'city': 'Islamabad'},
    {'loc': 'Judicial Town', 'city': 'Islamabad'},
    {'loc': 'Kahuta Road', 'city': 'Islamabad'},
    {'loc': 'Karakoram Diplomatic Enclave', 'city': 'Islamabad'},
    {'loc': 'Kashmir Highway', 'city': 'Islamabad'},
    {'loc': 'Kashmir Town', 'city': 'Islamabad'},
    {'loc': 'Khanna Pul', 'city': 'Islamabad'},
    {'loc': 'Khayaban-e-Iqbal', 'city': 'Islamabad'},
    {'loc': 'Koral Chowk', 'city': 'Islamabad'},
    {'loc': 'Koral Town', 'city': 'Islamabad'},
    {'loc': 'Korang Road', 'city': 'Islamabad'},
    {'loc': 'Korang Town', 'city': 'Islamabad'},
    {'loc': 'Kuri Road', 'city': 'Islamabad'},
    {'loc': 'Lawyers Society', 'city': 'Islamabad'},
    {'loc': 'Lehtarar Road', 'city': 'Islamabad'},
    {'loc': 'Madina Town', 'city': 'Islamabad'},
    {'loc': 'Main Margalla Road', 'city': 'Islamabad'},
    {'loc': 'Malot', 'city': 'Islamabad'},
    {'loc': 'Margalla Town', 'city': 'Islamabad'},
    {'loc': 'Margalla Valley - C-12', 'city': 'Islamabad'},
    {'loc': 'Marwa Town', 'city': 'Islamabad'},
    {'loc': 'Meherban Colony', 'city': 'Islamabad'},
    {'loc': 'Model Town', 'city': 'Islamabad'},
    {'loc': 'Mohra Nur Road', 'city': 'Islamabad'},
    {'loc': 'Motorway Chowk', 'city': 'Islamabad'},
    {'loc': 'Multi Residencia & Orchards', 'city': 'Islamabad'},
    {'loc': 'Mumtaz City', 'city': 'Islamabad'},
    {'loc': 'Murree Road', 'city': 'Islamabad'},
    {'loc': 'National Police Foundation', 'city': 'Islamabad'},
    {'loc': 'National Police Foundation O-9', 'city': 'Islamabad'},
    {'loc': 'Naval Anchorage', 'city': 'Islamabad'},
    {'loc': 'Naval Farms Housing Scheme', 'city': 'Islamabad'},
    {'loc': 'Naval Housing Scheme', 'city': 'Islamabad'},
    {'loc': 'New Airport Town', 'city': 'Islamabad'},
    {'loc': 'New Blue Area', 'city': 'Islamabad'},
    {'loc': 'New Icon City', 'city': 'Islamabad'},
    {'loc': 'New Shakrial', 'city': 'Islamabad'},
    {'loc': 'Nova City', 'city': 'Islamabad'},
    {'loc': 'OPF Valley', 'city': 'Islamabad'},
    {'loc': 'Orchard Scheme', 'city': 'Islamabad'},
    {'loc': 'Others', 'city': 'Islamabad'},
    {'loc': 'PAEC Employees Cooperative Housing Society', 'city': 'Islamabad'},
    {'loc': 'PAF Tarnol', 'city': 'Islamabad'},
    {'loc': 'PECHS', 'city': 'Islamabad'},
    {'loc': 'PTV Colony', 'city': 'Islamabad'},
    {'loc': 'PWD Housing Scheme', 'city': 'Islamabad'},
    {'loc': 'PWD Road', 'city': 'Islamabad'},
    {'loc': 'Pakistan Town', 'city': 'Islamabad'},
    {'loc': 'Park Enclave', 'city': 'Islamabad'},
    {'loc': 'Park Road', 'city': 'Islamabad'},
    {'loc': 'Park View City', 'city': 'Islamabad'},
    {'loc': 'Phulgran', 'city': 'Islamabad'},
    {'loc': 'Pind Begwal', 'city': 'Islamabad'},
    {'loc': 'Pindorian', 'city': 'Islamabad'},
    {'loc': 'Pir Sohawa', 'city': 'Islamabad'},
    {'loc': 'Police Foundation Housing Society', 'city': 'Islamabad'},
    {'loc': 'Qutbal Town', 'city': 'Islamabad'},
    {'loc': 'Rawal Enclave', 'city': 'Islamabad'},
    {'loc': 'Rawat', 'city': 'Islamabad'},
    {'loc': 'River Garden', 'city': 'Islamabad'},
    {'loc': 'Royal Avenue', 'city': 'Islamabad'},
    {'loc': 'Sanam Garden Housing Scheme', 'city': 'Islamabad'},
    {'loc': 'Sangjani', 'city': 'Islamabad'},
    {'loc': 'Sarai Kharbuza', 'city': 'Islamabad'},
    {'loc': 'Sehala Farm House', 'city': 'Islamabad'},
    {'loc': 'Shah Allah Ditta', 'city': 'Islamabad'},
    {'loc': 'Shaheen Town', 'city': 'Islamabad'},
    {'loc': 'Shahpur', 'city': 'Islamabad'},
    {'loc': 'Shalimar Town', 'city': 'Islamabad'},
    {'loc': 'Shehzad Town', 'city': 'Islamabad'},
    {'loc': 'Sihala', 'city': 'Islamabad'},
    {'loc': 'Sihala Valley', 'city': 'Islamabad'},
    {'loc': 'Simly Dam Road', 'city': 'Islamabad'},
    {'loc': 'Soan Garden', 'city': 'Islamabad'},
    {'loc': 'Sohan Valley', 'city': 'Islamabad'},
    {'loc': 'Spring Valley', 'city': 'Islamabad'},
    {'loc': 'Swan Garden', 'city': 'Islamabad'},
    {'loc': 'Taramrri', 'city': 'Islamabad'},
    {'loc': 'Tarlai', 'city': 'Islamabad'},
    {'loc': 'Tarnol', 'city': 'Islamabad'},
    {'loc': 'Thanda Pani', 'city': 'Islamabad'},
    {'loc': 'The Organic Farms Islamabad', 'city': 'Islamabad'},
    {'loc': 'The Springs', 'city': 'Islamabad'},
    {'loc': 'Top City 1', 'city': 'Islamabad'},
    {'loc': 'Tumair', 'city': 'Islamabad'},
    {'loc': 'University Town', 'city': 'Islamabad'},
    {'loc': 'Victoria Heights', 'city': 'Islamabad'},
    {'loc': 'Wapda Town', 'city': 'Islamabad'},
    {'loc': 'Zaraj Housing Scheme', 'city': 'Islamabad'},
    {'loc': 'Zone 5', 'city': 'Islamabad'},
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      bottomNavigationBar: Container(
        decoration: BoxDecoration(
          border: Border(top: BorderSide(width: 1, color: Color.fromARGB(50, 70, 50, 12))),
        ),
        child: Padding(
          padding: const EdgeInsets.only(left: 0, right: 0, top: 10, bottom: 10),
          child: Row(
            children: [
              Padding(
                padding: const EdgeInsets.only(left: 20, right: 20, top: 0, bottom: 0),
                child: Text(
                  'Save as Draft',
                  style: TextStyle(
                    fontSize: 16,
                    color: Colors.grey.shade700,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
              SizedBox(
                width: 200,
                height: 45,
                child: ElevatedButton(
                  onPressed: () {},
                  child: Text(
                    'Post Ad',
                    style: TextStyle(
                      fontSize: 16,
                      color: Colors.white,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
      body: CustomScrollView(
        slivers: [
          SliverAppBar(
            pinned: true,
            snap: false,
            floating: false,
            expandedHeight: 57,
            flexibleSpace: FlexibleSpaceBar(
              expandedTitleScale: 1,
              title: Text(
                'Post an Add',
                style: TextStyle(
                  fontSize: 16,
                ),
              ),
              background: Container(),
            ),
          ),
          SliverToBoxAdapter(
            child: Column(
              children: [
                Padding(
                  padding: const EdgeInsets.all(12),
                  child: Column(
                    children: [
                      Row(
                        children: [
                          Padding(
                            padding: const EdgeInsets.only(left: 20, right: 20),
                            child: Icon(
                              Icons.account_tree_sharp,
                              color: Colors.grey,
                            ),
                          ),
                          Text(
                            'Purpose',
                            style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                          ),
                        ],
                      ),
                      Row(
                        children: [
                          Padding(
                            padding: const EdgeInsets.only(left: 20, right: 0, top: 0, bottom: 0),
                            child: Container(
                              // width: 80,
                              decoration: BoxDecoration(
                                  border: Border.all(
                                    color: Colors.green,
                                    width: 1,
                                  ),
                                  borderRadius: BorderRadius.circular(50)),
                              child: Center(
                                child: Padding(
                                  padding: const EdgeInsets.only(left: 20, right: 20, top: 10, bottom: 10),
                                  child: Text(
                                    'Sell',
                                    style: TextStyle(
                                      fontSize: 14,
                                      fontWeight: FontWeight.bold,
                                      color: Colors.green,
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ),
                          Padding(
                            padding: const EdgeInsets.only(left: 10, right: 0, top: 0, bottom: 0),
                            child: Container(
                              // width: 80,
                              decoration: BoxDecoration(
                                  border: Border.all(
                                    color: Colors.grey.shade300,
                                    width: 1,
                                  ),
                                  borderRadius: BorderRadius.circular(50)),
                              child: Center(
                                child: Padding(
                                  padding: const EdgeInsets.only(left: 20, right: 20, top: 10, bottom: 10),
                                  child: Text(
                                    'Rent Out',
                                    style: TextStyle(
                                      fontSize: 14,
                                      fontWeight: FontWeight.bold,
                                      color: Colors.black,
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
                Divider(),
                Padding(
                  padding: const EdgeInsets.all(12),
                  child: Column(
                    children: [
                      Row(
                        children: [
                          Padding(
                            padding: const EdgeInsets.only(left: 20, right: 20),
                            child: Icon(
                              Icons.account_tree_sharp,
                              color: Colors.grey,
                            ),
                          ),
                          Text(
                            'Select Property Type',
                            style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                          ),
                        ],
                      ),
                      Container(height: 10),
                      Wrap(
                        spacing: 10,
                        runSpacing: 5,
                        runAlignment: WrapAlignment.start,
                        alignment: WrapAlignment.start,
                        crossAxisAlignment: WrapCrossAlignment.start,
                        children: [
                          IntrinsicWidth(
                            child: Container(
                              // width: 80,
                              decoration: BoxDecoration(
                                  border: Border.all(
                                    color: Colors.green,
                                    width: 1,
                                  ),
                                  borderRadius: BorderRadius.circular(50)),
                              child: Center(
                                child: Padding(
                                  padding: const EdgeInsets.only(left: 20, right: 20, top: 10, bottom: 10),
                                  child: Text(
                                    'House',
                                    style: TextStyle(
                                      fontSize: 14,
                                      fontWeight: FontWeight.bold,
                                      color: Colors.green,
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ),
                          IntrinsicWidth(
                            child: Container(
                              // width: 80,
                              decoration: BoxDecoration(
                                  border: Border.all(
                                    color: Colors.grey.shade300,
                                    width: 1,
                                  ),
                                  borderRadius: BorderRadius.circular(50)),
                              child: Center(
                                child: Padding(
                                  padding: const EdgeInsets.only(left: 20, right: 20, top: 10, bottom: 10),
                                  child: Text(
                                    'Flat',
                                    style: TextStyle(
                                      fontSize: 14,
                                      fontWeight: FontWeight.bold,
                                      color: Colors.black,
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ),
                          IntrinsicWidth(
                            child: Container(
                              // width: 80,
                              decoration: BoxDecoration(
                                  border: Border.all(
                                    color: Colors.grey.shade300,
                                    width: 1,
                                  ),
                                  borderRadius: BorderRadius.circular(50)),
                              child: Center(
                                child: Padding(
                                  padding: const EdgeInsets.only(left: 20, right: 20, top: 10, bottom: 10),
                                  child: Text(
                                    'Upper Portion',
                                    style: TextStyle(
                                      fontSize: 14,
                                      fontWeight: FontWeight.bold,
                                      color: Colors.black,
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ),
                          IntrinsicWidth(
                            child: Container(
                              // width: 80,
                              decoration: BoxDecoration(
                                  border: Border.all(
                                    color: Colors.grey.shade300,
                                    width: 1,
                                  ),
                                  borderRadius: BorderRadius.circular(50)),
                              child: Center(
                                child: Padding(
                                  padding: const EdgeInsets.only(left: 20, right: 20, top: 10, bottom: 10),
                                  child: Text(
                                    'Lower Portion',
                                    style: TextStyle(
                                      fontSize: 14,
                                      fontWeight: FontWeight.bold,
                                      color: Colors.black,
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ),
                          IntrinsicWidth(
                            child: Container(
                              // width: 80,
                              decoration: BoxDecoration(
                                  border: Border.all(
                                    color: Colors.grey.shade300,
                                    width: 1,
                                  ),
                                  borderRadius: BorderRadius.circular(50)),
                              child: Center(
                                child: Padding(
                                  padding: const EdgeInsets.only(left: 20, right: 20, top: 10, bottom: 10),
                                  child: Text(
                                    'Farm House',
                                    style: TextStyle(
                                      fontSize: 14,
                                      fontWeight: FontWeight.bold,
                                      color: Colors.black,
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ),
                          IntrinsicWidth(
                            child: Container(
                              // width: 80,
                              decoration: BoxDecoration(
                                  border: Border.all(
                                    color: Colors.grey.shade300,
                                    width: 1,
                                  ),
                                  borderRadius: BorderRadius.circular(50)),
                              child: Center(
                                child: Padding(
                                  padding: const EdgeInsets.only(left: 20, right: 20, top: 10, bottom: 10),
                                  child: Text(
                                    'Room',
                                    style: TextStyle(
                                      fontSize: 14,
                                      fontWeight: FontWeight.bold,
                                      color: Colors.black,
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ),
                          IntrinsicWidth(
                            child: Container(
                              // width: 80,
                              decoration: BoxDecoration(
                                  border: Border.all(
                                    color: Colors.grey.shade300,
                                    width: 1,
                                  ),
                                  borderRadius: BorderRadius.circular(50)),
                              child: Center(
                                child: Padding(
                                  padding: const EdgeInsets.only(left: 20, right: 20, top: 10, bottom: 10),
                                  child: Text(
                                    'Penthouse',
                                    style: TextStyle(
                                      fontSize: 14,
                                      fontWeight: FontWeight.bold,
                                      color: Colors.black,
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
                Divider(),
                Padding(
                  padding: const EdgeInsets.all(12),
                  child: Column(
                    children: [
                      Row(
                        children: [
                          Padding(
                            padding: const EdgeInsets.only(left: 20, right: 20),
                            child: Icon(
                              Icons.account_tree_sharp,
                              color: Colors.grey,
                            ),
                          ),
                          Text(
                            'City',
                            style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                          ),
                        ],
                      ),
                      SizedBox(
                        width: 260,
                        child: DropdownButtonFormField(
                            value: _selectedCity,
                            items: ['Karachi', 'Lahore', 'Islamabad', 'Pindi', 'Peshawar', 'Gawadar', 'Multan', 'Sialkot']
                                .map(
                                  (e) => DropdownMenuItem(
                                    value: e,
                                    child: Text(
                                      e,
                                    ),
                                  ),
                                )
                                .toList(),
                            onChanged: (c) {
                              setState(() {
                                _tmpLocations = [];
                                _selectedLocation = null;
                                _selectedCity = c ?? '';
                              });
                              Future.delayed(Duration(milliseconds: 1000), () {
                                setState(() {
                                  // _tmpLocations =
                                  //     _locations.where((element) => element['city'] == _selectedCity).toList();
                                });
                              });

                            }),
                      ),
                      Container(
                        height: 20,
                      ),
                      // SizedBox(
                      //   width: 260,
                      //   child: DropdownButtonFormField(
                      //       value: _selectedLocation,
                      //       items: _tmpLocations
                      //           .map(
                      //             (e) => DropdownMenuItem(
                      //               value: e['loc'],
                      //               child: Text(
                      //                 '${e['loc']}',
                      //               ),
                      //             ),
                      //           )
                      //           .toList(),
                      //       onChanged: (c) {}),
                      // ),
                    ],
                  ),
                ),
                Divider(),
                Container(
                  height: 250,
                  child: Text(
                    '  ',
                  ),
                ),
                Text(' '),
                Text(' '),
              ],
            ),
          )
        ],
      ),
    );
  }
}
